import type { RsvpConfiguration } from '../../rsvpConfiguration/types'
import type { RsvpFormValues } from '../rsvpSchema'
import type { InvitationGuest } from '../types'
import { AttendanceStatusBadge } from './AttendanceStatusBadge'

type Props = { values: RsvpFormValues; invitedGuests: InvitationGuest[]; configuration: RsvpConfiguration }
function OptionalValue({ value }: { value: string }) { return value.trim() ? <span>{value.trim()}</span> : <span className="text-[var(--color-muted)]">Not provided</span> }

export function RsvpReview({ values, invitedGuests, configuration }: Props) {
  const guestQuestions = configuration.guestQuestions.filter((question) => question.enabled && question.key !== 'attendance')
  const householdQuestions = configuration.householdQuestions.filter((question) => question.enabled)
  return <section><h2 className="font-[var(--font-display)] text-3xl">Review your RSVP</h2><p className="mt-2 text-[var(--color-muted)]">Please make sure every household member’s response is correct before confirming.</p><div className="mt-6 space-y-4">{values.guests.map((guest, index) => <section key={guest.id} className="rounded-[var(--radius-lg)] border border-[var(--color-border)] bg-[var(--color-surface)] p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="font-[var(--font-display)] text-xl">{invitedGuests[index]?.fullName}</h3><AttendanceStatusBadge status={guest.attendanceStatus} /></div>{guest.attendanceStatus === 'attending' && guestQuestions.length ? <dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2">{guestQuestions.map((question) => <div key={question.key}><dt className="font-medium">{question.label}</dt><dd className="mt-1 text-[var(--color-muted)]"><OptionalValue value={question.key === 'dietaryRequirements' ? guest.dietaryRequirements : guest.accessibilityRequirements} /></dd></div>)}</dl> : null}</section>)}</div>{householdQuestions.length ? <section className="mt-4 rounded-[var(--radius-lg)] border border-[var(--color-border)] bg-[var(--color-surface)] p-5"><h3 className="font-[var(--font-display)] text-xl">Household details</h3><dl className="mt-4 grid gap-4 text-sm sm:grid-cols-2">{householdQuestions.map((question) => { const value = question.key === 'responsePhone' ? values.contactNumber : question.key === 'responseEmail' ? values.email : values.message; return <div key={question.key} className={question.key === 'messageToCouple' ? 'sm:col-span-2' : ''}><dt className="font-medium">{question.label}</dt><dd className="mt-1 break-words whitespace-pre-wrap text-[var(--color-muted)]"><OptionalValue value={value} /></dd></div> })}</dl></section> : null}</section>
}
