import { motion, useReducedMotion } from 'framer-motion'
import { ArrowDown, CalendarDays } from 'lucide-react'
import { formatWeddingDate } from '../../../lib/utils/formatDate'
import type { PublicWeddingDetails } from '../types'
import { weddingCountdown } from '../utils'

export function WeddingHero({ wedding }: { wedding: PublicWeddingDetails }) {
  const reduceMotion = useReducedMotion()
  const countdown = weddingCountdown(wedding.weddingDate)
  return <section id="top" className="relative isolate flex min-h-[78vh] scroll-mt-24 items-center overflow-hidden px-5 py-20 text-center sm:px-8"><div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_20%_20%,color-mix(in_srgb,var(--color-secondary)_18%,transparent),transparent_35%),radial-gradient(circle_at_80%_70%,color-mix(in_srgb,var(--color-accent)_14%,transparent),transparent_38%)]" aria-hidden="true" /><div className="absolute left-1/2 top-1/2 -z-10 aspect-square w-[min(80vw,42rem)] -translate-x-1/2 -translate-y-1/2 rounded-full border border-[color-mix(in_srgb,var(--color-border)_70%,transparent)]" aria-hidden="true" /><motion.div initial={reduceMotion ? false : { opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: reduceMotion ? 0 : 0.55 }} className="mx-auto max-w-5xl"><p className="text-xs font-semibold uppercase tracking-[0.3em] text-[var(--color-muted)]">We're getting married</p><h1 className="mt-6 font-[var(--font-display)] text-5xl leading-[0.95] text-[var(--color-primary)] sm:text-7xl lg:text-8xl">{wedding.partnerOneName}<span className="mx-3 block text-[0.55em] italic text-[var(--color-accent)] sm:inline" aria-hidden="true">&amp;</span>{wedding.partnerTwoName}</h1><p className="mt-8 inline-flex items-center gap-2 text-base tracking-wide sm:text-lg"><CalendarDays className="size-5" aria-hidden="true" />{formatWeddingDate(wedding.weddingDate)}</p><div className="mt-8" aria-label={countdown.value === null ? countdown.label : `${countdown.value} ${countdown.label}`}>{countdown.value === null || countdown.value === 0 ? <p className="font-[var(--font-display)] text-2xl">{countdown.label}</p> : <><p className="font-[var(--font-display)] text-5xl tabular-nums">{countdown.value}</p><p className="mt-1 text-sm uppercase tracking-[0.18em] text-[var(--color-muted)]">{countdown.label}</p></>}</div><div className="mt-10 flex flex-wrap justify-center gap-3"><a href="#rsvp" className="inline-flex min-h-12 items-center rounded-full bg-[var(--color-primary)] px-7 font-semibold text-white">RSVP</a><a href="#details" className="inline-flex min-h-12 items-center gap-2 rounded-full border border-[var(--color-border)] bg-[var(--color-surface)] px-7 font-semibold">Wedding details <ArrowDown className="size-4" aria-hidden="true" /></a></div></motion.div></section>
}
