/* eslint-disable react-refresh/only-export-components -- Template presentation components are intentionally packaged as one static contract. */
import { Check, LockKeyhole } from 'lucide-react'
import type { ReactNode } from 'react'
import { ActionButton } from '../../../../components/ui/ActionButton'
import { formatWeddingDate } from '../../../../lib/utils/formatDate'
import { AttendanceStatusBadge } from '../../../invitation/components/AttendanceStatusBadge'
import type { PublicInvitation, WeddingSummary } from '../../../invitation/types'
import type { RsvpConfirmationProps, RsvpPresentation } from '../../types'

function Shell({ children }: { children: ReactNode }) {
  return <article id="rsvp" className="mx-auto max-w-4xl scroll-mt-20 border-x border-[var(--color-border)] bg-[var(--color-background)] px-5 py-8 sm:px-10 sm:py-12">{children}</article>
}

function Overview({ invitation, wedding }: { invitation: PublicInvitation; wedding: WeddingSummary }) {
  return <header className="mb-10 border-b border-[var(--color-text)] pb-8"><div className="grid gap-8 md:grid-cols-[1fr_auto] md:items-end"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-[var(--color-accent)]">Household invitation</p><h1 className="mt-4 font-[var(--font-display)] text-4xl leading-none text-[var(--color-primary)] sm:text-6xl">{invitation.displayName}</h1><p className="mt-5 text-sm font-bold uppercase tracking-[0.12em]">{wedding.partnerOneName} / {wedding.partnerTwoName}</p></div><dl className="grid min-w-56 gap-4 text-sm"><div className="border-t border-[var(--color-border)] pt-3"><dt className="text-xs font-bold uppercase tracking-wider text-[var(--color-muted)]">Date</dt><dd className="mt-1 font-semibold">{formatWeddingDate(wedding.weddingDate)}</dd></div><div className="border-t border-[var(--color-border)] pt-3"><dt className="text-xs font-bold uppercase tracking-wider text-[var(--color-muted)]">Dress</dt><dd className="mt-1 font-semibold">{wedding.dressCode || 'Details to follow'}</dd></div></dl></div></header>
}

function Confirmation({ invitation, readOnly = false, notice, onEdit }: RsvpConfirmationProps) {
  return <section className="mx-auto max-w-4xl"><header className="grid gap-5 border-b border-[var(--color-text)] pb-8 sm:grid-cols-[3rem_1fr]">{readOnly ? <LockKeyhole className="size-8 text-[var(--color-muted)]" aria-hidden="true" /> : <span className="flex size-10 items-center justify-center bg-[var(--color-primary)] text-white"><Check className="size-5" aria-hidden="true" /></span>}<div><p className="text-xs font-black uppercase tracking-[0.2em] text-[var(--color-accent)]">Response status</p><h1 className="mt-3 font-[var(--font-display)] text-4xl text-[var(--color-primary)]">{invitation.hasSubmitted ? 'RSVP received.' : 'Responses closed.'}</h1><p className="mt-3 max-w-2xl text-[var(--color-muted)]">{notice ?? (invitation.hasSubmitted ? 'Your household response is recorded below.' : 'This invitation is no longer accepting responses.')}</p></div></header><section className="mt-8"><h2 className="text-xs font-black uppercase tracking-[0.2em]">Household / {invitation.guests.length}</h2><ul className="mt-4 border-t border-[var(--color-border)]">{invitation.guests.map((guest) => <li key={guest.id} className="grid gap-3 border-b border-[var(--color-border)] py-5 sm:grid-cols-[1fr_auto] sm:items-start"><div><p className="font-bold">{guest.fullName}</p>{guest.attendanceStatus === 'attending' && (guest.dietaryRequirements || guest.accessibilityRequirements) ? <div className="mt-2 text-sm leading-6 text-[var(--color-muted)]">{guest.dietaryRequirements ? <p>Dietary / {guest.dietaryRequirements}</p> : null}{guest.accessibilityRequirements ? <p>Accessibility / {guest.accessibilityRequirements}</p> : null}</div> : null}</div><AttendanceStatusBadge status={guest.attendanceStatus} /></li>)}</ul></section>{(invitation.responseContactNumber || invitation.responseEmail || invitation.messageToCouple) ? <section className="mt-8 border-l-4 border-[var(--color-accent)] bg-[var(--color-surface)] p-6"><h2 className="text-xs font-black uppercase tracking-[0.2em]">Household details</h2><dl className="mt-5 grid gap-5 text-sm sm:grid-cols-2">{invitation.responseContactNumber ? <div><dt className="font-bold">Contact</dt><dd className="mt-1 text-[var(--color-muted)]">{invitation.responseContactNumber}</dd></div> : null}{invitation.responseEmail ? <div><dt className="font-bold">Email</dt><dd className="mt-1 break-words text-[var(--color-muted)]">{invitation.responseEmail}</dd></div> : null}{invitation.messageToCouple ? <div className="sm:col-span-2"><dt className="font-bold">Message</dt><dd className="mt-1 whitespace-pre-wrap text-[var(--color-muted)]">{invitation.messageToCouple}</dd></div> : null}</dl></section> : null}{invitation.canRespond && onEdit ? <div className="mt-8"><ActionButton onClick={onEdit}>Edit RSVP</ActionButton></div> : null}</section>
}

export const modernMinimalRsvpPresentation: RsvpPresentation = { Shell, Overview, Confirmation }
