import { ArrowDown, ArrowUpRight, CalendarDays, ChevronDown, MapPin } from 'lucide-react'
import { useState } from 'react'
import { formatWeddingDate } from '../../../../lib/utils/formatDate'
import { ContentImage } from '../../../publicWedding/components/ContentImage'
import type { PublicWedding, WeddingEvent, WeddingFaqEntry } from '../../../publicWedding/types'
import { formatWeddingTime, weddingCountdown } from '../../../publicWedding/utils'
import { ModernMinimalShell } from './components/ModernMinimalShell'

const eventLabels = { ceremony: 'Ceremony', reception: 'Reception', other: 'Event' } as const

function ModernHero({ wedding }: { wedding: PublicWedding }) {
  const hero = wedding.content?.hero ?? null
  const countdown = weddingCountdown(wedding.weddingDate)
  const title = hero?.headline || `${wedding.partnerOneName} / ${wedding.partnerTwoName}`

  return <section id="top" className="scroll-mt-20 border-b border-[var(--color-border)] px-5 py-12 sm:px-8 sm:py-18"><div className={`mx-auto grid max-w-7xl gap-10 ${hero?.mediaUrl ? 'lg:grid-cols-[minmax(0,0.9fr)_minmax(24rem,1.1fr)]' : ''}`}><div className="flex min-h-[30rem] flex-col justify-between"><p className="text-xs font-black uppercase tracking-[0.22em] text-[var(--color-accent)]">{hero?.eyebrow || 'Wedding announcement'}</p><div className="py-14"><h1 className="max-w-4xl font-[var(--font-display)] text-5xl leading-[0.92] text-[var(--color-primary)] sm:text-7xl lg:text-8xl">{title}</h1>{hero?.headline ? <p className="mt-6 text-xl font-semibold">{wedding.partnerOneName} / {wedding.partnerTwoName}</p> : null}{hero?.subheadline ? <p className="mt-6 max-w-2xl whitespace-pre-line text-lg leading-8 text-[var(--color-muted)]">{hero.subheadline}</p> : null}</div><div className="grid gap-5 border-t border-[var(--color-border)] pt-6 sm:grid-cols-[1fr_auto] sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[var(--color-muted)]">Date</p><p className="mt-2 text-lg font-semibold">{formatWeddingDate(wedding.weddingDate)}</p></div><div className="sm:text-right"><p className="text-4xl font-black tabular-nums">{countdown.value ?? '—'}</p><p className="text-xs uppercase tracking-wider text-[var(--color-muted)]">{countdown.label}</p></div></div></div>{hero?.mediaUrl ? <ContentImage src={hero.mediaUrl} alt={hero.mediaAltText} eager className="min-h-[30rem] h-full w-full border border-[var(--color-border)] object-cover" /> : null}</div><div className="mx-auto mt-10 flex max-w-7xl flex-wrap gap-3"><a href="#details" className="inline-flex min-h-12 items-center gap-2 bg-[var(--color-primary)] px-6 font-bold text-white">View details <ArrowDown className="size-4" aria-hidden="true" /></a><a href="#rsvp" className="inline-flex min-h-12 items-center border border-[var(--color-text)] px-6 font-bold">RSVP</a></div></section>
}

function ModernStory({ wedding }: { wedding: PublicWedding }) {
  const entries = wedding.content?.story ?? []
  if (!entries.length) return null
  return <section id="story" className="scroll-mt-20 px-5 py-20 sm:px-8 sm:py-28"><div className="mx-auto max-w-7xl"><div className="grid gap-6 border-b border-[var(--color-border)] pb-8 md:grid-cols-[12rem_1fr]"><p className="text-xs font-black uppercase tracking-[0.2em] text-[var(--color-accent)]">01 / Story</p><h2 className="max-w-3xl font-[var(--font-display)] text-4xl sm:text-6xl">A shared history, in sequence.</h2></div><div>{entries.map((entry, index) => <article key={entry.id} className="grid gap-8 border-b border-[var(--color-border)] py-10 md:grid-cols-[6rem_minmax(0,1fr)_minmax(0,1.2fr)] md:py-14"><p className="text-sm font-black tabular-nums text-[var(--color-accent)]">{String(index + 1).padStart(2, '0')}</p><div>{entry.eventDate ? <p className="text-xs font-bold uppercase tracking-wider text-[var(--color-muted)]">{formatWeddingDate(entry.eventDate)}</p> : null}{entry.title ? <h3 className="mt-3 font-[var(--font-display)] text-3xl">{entry.title}</h3> : null}<p className="mt-4 whitespace-pre-line leading-8 text-[var(--color-muted)]">{entry.body}</p></div>{entry.imageUrl ? <ContentImage src={entry.imageUrl} alt={entry.imageAltText} className="aspect-[16/10] w-full border border-[var(--color-border)] object-cover" /> : <div className="hidden bg-[var(--color-surface)] md:block" aria-hidden="true" />}</article>)}</div></div></section>
}

function EventCard({ event }: { event: WeddingEvent }) {
  return <article className="grid border-t border-[var(--color-border)] py-7 sm:grid-cols-[9rem_1fr_auto] sm:gap-6"><div><p className="text-xs font-black uppercase tracking-wider text-[var(--color-accent)]">{eventLabels[event.eventType]}</p><p className="mt-2 font-semibold">{formatWeddingDate(event.eventDate)}</p>{event.startTime ? <p className="mt-1 text-sm text-[var(--color-muted)]">{formatWeddingTime(event.startTime)}{event.endTime ? ` – ${formatWeddingTime(event.endTime)}` : ''}</p> : null}</div><div className="mt-5 sm:mt-0"><h3 className="font-[var(--font-display)] text-3xl">{event.title}</h3>{event.venueName ? <p className="mt-3 font-semibold">{event.venueName}</p> : null}{event.addressLine ? <p className="mt-1 whitespace-pre-line text-sm text-[var(--color-muted)]">{event.addressLine}</p> : null}{event.description ? <p className="mt-4 max-w-2xl whitespace-pre-line leading-7 text-[var(--color-muted)]">{event.description}</p> : null}{event.dressCodeOverride ? <p className="mt-4 text-sm"><span className="font-bold">Dress:</span> {event.dressCodeOverride}</p> : null}</div>{event.mapUrl ? <a href={event.mapUrl} target="_blank" rel="noopener noreferrer" className="mt-5 inline-flex min-h-11 items-center gap-2 self-start text-sm font-black uppercase tracking-wider sm:mt-0">Map <ArrowUpRight className="size-4" aria-hidden="true" /></a> : null}</article>
}

function ModernDetails({ wedding }: { wedding: PublicWedding }) {
  const events = wedding.content?.events ?? []
  return <section id="details" className="scroll-mt-20 bg-[var(--color-surface)] px-5 py-20 sm:px-8 sm:py-28"><div className="mx-auto max-w-7xl"><div className="grid gap-6 pb-10 md:grid-cols-[12rem_1fr]"><p className="text-xs font-black uppercase tracking-[0.2em] text-[var(--color-accent)]">02 / Schedule</p><h2 className="font-[var(--font-display)] text-4xl sm:text-6xl">Where to be.</h2></div>{events.length ? events.map((event) => <EventCard key={event.id} event={event} />) : <div className="grid gap-6 border-t border-[var(--color-border)] py-10 sm:grid-cols-2"><div><CalendarDays className="size-5" aria-hidden="true" /><h3 className="mt-4 text-2xl font-bold">Save the date</h3><p className="mt-2 text-[var(--color-muted)]">{formatWeddingDate(wedding.weddingDate)}</p></div><div><MapPin className="size-5" aria-hidden="true" /><h3 className="mt-4 text-2xl font-bold">Location</h3><p className="mt-2 text-[var(--color-muted)]">Venue and timing details will follow.</p></div></div>}</div></section>
}

function ModernGallery({ wedding }: { wedding: PublicWedding }) {
  const entries = wedding.content?.gallery ?? []
  if (!entries.length) return null
  return <section id="gallery" className="scroll-mt-20 px-5 py-20 sm:px-8 sm:py-28"><div className="mx-auto max-w-7xl"><div className="flex items-end justify-between gap-6 border-b border-[var(--color-border)] pb-8"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-[var(--color-accent)]">03 / Gallery</p><h2 className="mt-3 font-[var(--font-display)] text-4xl sm:text-6xl">Selected moments.</h2></div><p className="hidden text-sm tabular-nums text-[var(--color-muted)] sm:block">{String(entries.length).padStart(2, '0')} images</p></div><div className="mt-8 grid auto-rows-[12rem] gap-3 sm:grid-cols-2 lg:grid-cols-12">{entries.map((entry, index) => <figure key={entry.id} className={`group relative overflow-hidden border border-[var(--color-border)] ${index % 5 === 0 ? 'sm:row-span-2 lg:col-span-7' : index % 3 === 0 ? 'lg:col-span-7' : 'lg:col-span-5'}`}><ContentImage src={entry.imageUrl} alt={entry.altText} className="h-full w-full object-cover transition-transform duration-500 motion-reduce:transition-none group-hover:scale-[1.02]" />{entry.caption ? <figcaption className="absolute inset-x-0 bottom-0 bg-[color-mix(in_srgb,var(--color-primary)_88%,transparent)] px-4 py-3 text-sm text-white">{entry.caption}</figcaption> : null}</figure>)}</div></div></section>
}

function ModernFaq({ entries }: { entries: WeddingFaqEntry[] }) {
  const [open, setOpen] = useState<Set<number>>(() => new Set())
  if (!entries.length) return null
  return <section id="faq" className="scroll-mt-20 bg-[var(--color-surface)] px-5 py-20 sm:px-8 sm:py-28"><div className="mx-auto max-w-5xl"><p className="text-xs font-black uppercase tracking-[0.2em] text-[var(--color-accent)]">04 / Information</p><h2 className="mt-3 font-[var(--font-display)] text-4xl sm:text-6xl">Questions, answered.</h2><div className="mt-10 border-t border-[var(--color-text)]">{entries.map((entry) => { const expanded = open.has(entry.id); const panelId = `modern-faq-answer-${entry.id}`; return <article key={entry.id} className="border-b border-[var(--color-border)]"><h3><button type="button" className="flex min-h-16 w-full items-center justify-between gap-6 py-5 text-left text-lg font-bold sm:text-xl" aria-expanded={expanded} aria-controls={panelId} onClick={() => setOpen((current) => { const next = new Set(current); if (next.has(entry.id)) next.delete(entry.id); else next.add(entry.id); return next })}><span>{entry.question}</span><ChevronDown className={`size-5 shrink-0 transition-transform motion-reduce:transition-none ${expanded ? 'rotate-180' : ''}`} aria-hidden="true" /></button></h3><div id={panelId} hidden={!expanded} className="max-w-3xl pb-6"><p className="whitespace-pre-line leading-8 text-[var(--color-muted)]">{entry.answer}</p></div></article> })}</div></div></section>
}

function ModernRsvp({ wedding }: { wedding: PublicWedding }) {
  return <section id="rsvp" className="scroll-mt-20 bg-[var(--color-primary)] px-5 py-20 text-white sm:px-8 sm:py-24"><div className="mx-auto grid max-w-7xl gap-8 md:grid-cols-[1fr_auto] md:items-end"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-white/70">Your response</p><h2 className="mt-4 max-w-3xl font-[var(--font-display)] text-4xl sm:text-6xl">Join us for the day.</h2><p className="mt-5 max-w-2xl leading-7 text-white/75">Use the personalized invitation link sent to your household to respond for every named guest.</p>{wedding.rsvpDeadline ? <p className="mt-4 text-sm font-bold">Please reply by {formatWeddingDate(wedding.rsvpDeadline)}.</p> : null}</div><a href="#top" className="inline-flex min-h-12 items-center justify-center gap-2 border border-white px-6 font-bold">Back to top <ArrowDown className="size-4 rotate-180" aria-hidden="true" /></a></div></section>
}

export function ModernMinimalLandingPage({ wedding }: { wedding: PublicWedding }) {
  const content = wedding.content
  const visibleSections = { story: Boolean(content?.story?.length), gallery: Boolean(content?.gallery?.length), faq: Boolean(content?.faq?.length) }
  return <ModernMinimalShell wedding={wedding} visibleSections={visibleSections}><ModernHero wedding={wedding} /><ModernStory wedding={wedding} /><ModernDetails wedding={wedding} />{wedding.dressCode ? <section className="border-y border-[var(--color-text)] bg-[var(--color-secondary)] px-5 py-12 sm:px-8"><div className="mx-auto grid max-w-7xl gap-4 md:grid-cols-[12rem_1fr]"><p className="text-xs font-black uppercase tracking-[0.2em]">Dress code</p><p className="font-[var(--font-display)] text-3xl sm:text-5xl">{wedding.dressCode}</p></div></section> : null}<ModernGallery wedding={wedding} /><ModernFaq entries={content?.faq ?? []} /><ModernRsvp wedding={wedding} /></ModernMinimalShell>
}
